# Native PipeWire Declarative Virtual Microphone Configuration
# Creates an isolated Virtual Microphone Input for remote audio streaming
context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Mic (DESKTOP-156PNC1)"
            capture.props = {
                node.name = "remote_mic_sink"
                node.description = "Mic-Loopback-Sink"
                media.class = "Audio/Sink"
                node.virtual = true
                node.passive = true
                priority.session = 0
                priority.driver = 0
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name = "remote_mic_source"
                node.description = "Mic (DESKTOP-156PNC1)"
                media.class = "Audio/Source"
                node.virtual = true
                audio.position = [ FL FR ]
            }
        }
    }
]
