# Allow members of wheel and video groups to set negative nice and realtime priorities
# Needed for Sunshine stream priority, low-latency gaming, and PipeWire audio.
@wheel           soft    nice            -15
@wheel           hard    nice            -20
@wheel           soft    rtprio          99
@wheel           hard    rtprio          99
