# Declarative QEMU configuration for Bazzite-DX Silver Goggles
# Optimized for Looking Glass (KVMFR) and High-Performance Virtualization

cgroup_device_acl = [
    "/dev/null", "/dev/full", "/dev/zero",
    "/dev/random", "/dev/urandom",
    "/dev/ptmx", "/dev/kvm",
    "/dev/userfaultfd", "/dev/kvmfr0"
]
