[Service]
# Workaround for KRDP blank screen caused by buggy VAAPI drivers
# https://discuss.kde.org/t/krdp-help-blank-screen-on-connect/41952/5
Environment=KPIPEWIRE_FORCE_ENCODER=libx264
Environment=LIBVA_DRIVERS_PATH=/nonexistent
Environment=LIBVA_DRIVER_NAME=dummy
