---
name: Build Bazzite DX Silver Goggles
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  repository_dispatch:
    types:
      - build
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint & Validate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Install blue-build CLI
        run: |
          podman run --pull always --rm ghcr.io/blue-build/cli:latest-installer | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Validation
        run: just check

  bluebuild:
    name: Build Custom Image
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Generate Recipe
        run: just generate-recipe "bazzite-nvidia" "latest"

      - name: Build Custom Image
        uses: blue-build/github-action@24d146df25adc2cf579e918efe2d9bff6adea408 # v1.11.1
        with:
          recipe: .bluebuild/build-recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          skip_checkout: true
          maximize_build_space: true
          rechunk: false
          build_chunked_oci: true
          # Custom build options (conditional signing)
          build_opts: "${{ secrets.SIGNING_SECRET == '' && '--no-sign' || '' }}"
